-- LIKE 사용
SELECT DISTINCT(CITY)
FROM STATION
WHERE CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%';

-- IN 사용
SELECT DISTINCT(CITY)
FROM STATION
WHERE SUBSTR(CITY, 0, 1) IN ('A', 'E', 'I', 'O', 'U');